'''
createBoard creates a 2d array and returns it
It takes one parameter:
- boardSize: representing the size of the board created
Returns:
- List of Lists representing the board
'''
def createBoard(boardSize):
    board = []
    for row in range(boardSize):
        board.append([])
        for col in range(boardSize):
            board[row].append(0)
    return board

'''
printBoard prints out (in a formatted way) the board
Parameters:
- board: A list of lists generated by createBoard
Returns:
nothing
'''
def printBoard(world):
    outputString = "" #empty string
    board = world["board"]
    for row in range(len(board)):
        
        for col in range(len(board)):
            if world["playerLoc"]["x"]== col and world["playerLoc"]["y"]== row:
                outputString += f"[{"X":2}]"
            elif board[row][col] == 0:

                outputString += f"[{"":2}]"
        outputString += "\n"
    print(outputString, end="")
    for row in range(len(board)):
        
        for col in range(len(board)):
            if world["enemy1loc"]["x"]== col and world["enemy1loc"]["y"]== row:
                outputString += f"[{"E":2}]"
            elif board[row][col] == 0:

                outputString += f"[{"":2}]"
        outputString += "\n"
    print(outputString, end="")